{
 "title": "march_data",
 "time": { "from": "2024-03-01T00:00:00.000Z", "to": "2024-03-31T00:00:00.000Z" },
 "panels": [
  {
   "title": "fare_quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fare_amount_quantile FROM march_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "trip_distance_drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", trip_distance_drift FROM march_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "drifted_columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM march_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "missing_values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM march_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "prediction_drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM march_data LIMIT 50 "
    }
   ]
  }
 ]
}